# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - uses: fregante/setup-git-user@v1
      
      - run: npm install -g gatsby-cli gh-pages
      - run: npm install
      
      - name: Build
        run: gatsby build
      
      - name: Set CNAME
        run: echo "blog.frec.kr" > ./public/CNAME
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.REPO_HOOK_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
          SCRIPT_MODE: true
